@startuml

abstract class MessengerUser {
    id
    Address
    Language
    Settings
    messengers:Messenger[]
}

class Messenger {
    telephone
    email
    username
}

abstract class Message {
    messageID
    userID
}

class Answer

Answer --|> Message

class Request

Request --|> Message

MessengerUser -- Messenger

@enduml