@startuml
enum Messenger

class Message {
    ID: Long
    messageID: String
    senderID: String
    messenger: Messenger
    text: String
    attechments: Attachment[]
}

Message - Messenger
Message -- Attachment

@enduml