/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.bht.chatbot.drools

import java.util.List
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;

import java.time.LocalDate;

import de.bht.chatbot.canteen.model.Dish
import de.bht.chatbot.canteen.model.DishType;
import de.bht.chatbot.message.Intent;
import de.bht.chatbot.message.EntityName;
import de.bht.chatbot.drools.model.DroolsMessage;

global de.bht.chatbot.canteen.model.CanteenData canteenData;

// ---------------------- GREETING ------------------------------------
rule "Hello Drools"
   dialect "java"
   when
       m : DroolsMessage( intent.equals(Intent.HELLO.getText()))
   then
       modify ( m ) { setText("Guten Tag.")};
end

// ---------------------- SAYING GOODBYE ------------------------------------

rule "Saying goodbye"
    dialect "java"
    when
        m : DroolsMessage( intent.equals(Intent.BYE.getText()))
    then
        modify( m ) {
            setText("Auf Wiedersehen. Bis dann."),
            setAsVoiceMessage(true)
        };
end

// ------------------------ SHOW DISHES --------------------------------------

rule "Show all dishes"
    dialect "java"
    when
        m : DroolsMessage( intent.equals(Intent.SHOW_FOOD.getText()) && entities.isEmpty())
    then
        modify ( m ) { setText("Alle Gerichte dieser und nächster Woche: \n" + canteenData.getDishes())};
end

rule "Restaurant search"
    dialect "java"
    when
        m : DroolsMessage( intent.equals(Intent.RESTAURANT_SEARCH.getText()))
    then
        modify ( m ){ setText("Restaurant gesucht")}
end


rule "Show dishes filtered"
    dialect "java"
    when
        m : DroolsMessage( getIntent().equals(Intent.SHOW_FOOD.getText()) && !entities.isEmpty() )
    then
        modify( m ) {
            setText("Gerichte:\n" + canteenData.getDishesFilteredAsString(
            (m.getEntities().containsKey(EntityName.DATE.getText()) ? m.getEntities().get(EntityName.DATE.getText()) : null),
            (m.getEntities().containsKey(EntityName.HEALTHY.getText()) ? m.getEntities().get(EntityName.HEALTHY.getText()) : null),
            (m.getEntities().containsKey(EntityName.DISH_TYPE.getText()) ? m.getEntities().get(EntityName.DISH_TYPE.getText()) : null),
            (m.getEntities().containsKey(EntityName.INGREDIENTS.getText()) ? m.getEntities().get(EntityName.INGREDIENTS.getText()) : null),
            (m.getEntities().containsKey(EntityName.DISH_CATEGORY.getText()) ? m.getEntities().get(EntityName.DISH_CATEGORY.getText()) : null)
            ))
        };
end
// ----------------------------- START ---------------------------
rule "Start"
    dialect "java"
    when
        m : DroolsMessage( getIntent().equals(Intent.START.getText()))
    then
        modify(m) {setText("Hallo und herzlich willkommen!\n\n Ich bin der BeuthBot.\n Ich gebe dir gerne aktuelle Informationen der Gerichte der Mensa.")}
end

// ---------------------------- PRICE -----------------------------
rule "Show price"
    dialect "java"
    when
        m : DroolsMessage(getIntent().equals(Intent.SHOW_PRICE.getText()))
    then
        modify(m){setText(canteenData.showPriceOfDish(m.getEntities().containsKey(EntityName.DISH_NAME.getText()) ? m.getEntities().get(EntityName.DISH_NAME.getText()) : ""))}
end

// --------------------------- Fallback -------------------------
rule "Fallback"
    dialect "java"
    when
        m : DroolsMessage(getIntent().equals(Intent.FALLBACK.getText()))
    then
        modify(m){setText("Die Anfrage konnte ich leider nicht verarbeiten. \nVersuche eine genauere Formulierung.")}
end