/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package drools

import message.BotMessage

// TODO sja: Hier würde dann erneut der Cache stehen
// global java.bla.keks.Cache cache

rule "Test Rule"
    dialect "java"
    when
        m : BotMessage( intent == "Test")
    then
        modify ( m ) { setAnswer("Test successful" )};
end

rule "Show all meals"
    dialect "java"
    when
        m : BotMessage( intent == "show_meals")
    then
        modify ( m ) { setAnswer("Heute gibt es folgende Gerichte: \n" )};
end