package de.bht.beuthbot.conf;

/**
 * @author: georg.glossmann@adesso.de
 * Date: 03.07.17
 */
public enum Configuration {
    WEB_URL, TELEGRAM_WEBHOOK_URL, TELEGRAM_BOT_TOKEN, FACEBOOK_WEBHOOK_TOKEN, FACEBOOK_BOT_TOKEN, API_AI_TOKEN, BING_SPEECH_LOCALE, BING_SPEECH_GUID, BING_SPEECH_SECRET_KEY, LOCAL_ATTACHMENT_PATH;
}
